version: "3.9"
services:
  vue-app:
    image: node:20.11.1-slim
    tty: true
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/app
    command: sh -c "npm i && npm run dev --host"
    ports:
    - "5173:5173"
    - "8081:8081"