version: "3.9"
services:
  vue-app:
    image: node:20.11.1-slim
    tty: true
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/app
    command: sh -c "npm i @rollup/rollup-linux-arm64-gnu && npm run dev"
    ports:
    - "5173:5173"