name: format_check

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test action"
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Format
        run: npm run github-prettier-action
